[application]
name = "speak-notes"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "src/assets"

[web.app]
title = "Speak Notes"

[web.watcher]
reload_html = true
watch_path = ["src"]

[web.resource]
style = []
script = []

[bundle]
identifier = "com.speak-notes.app"
icon = []
resources = ["src/assets"]
copyright = "Copyright © 2025"
category = "Productivity"
short_description = "A speech recognition application built with Dioxus"
long_description = """
Speak Notes is a speech recognition application that allows you to transcribe your voice into text.
It uses the Web Speech API for speech recognition and provides features like saving, sharing, and downloading transcripts.
"""

[bundle.deb]
depends = []

[bundle.macos]
minimum_system_version = "10.13"
frameworks = []
